#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

export function readFlatCatalog(text, name = "catalog") {
  const value = JSON.parse(text);
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${name}: expected a flat object`);
  // JSON.parse silently accepts duplicate keys; catalogs are flat, so count lexical member keys.
  const keys = [...text.matchAll(/(?:^|[,\{])\s*("(?:[^"\\]|\\.)*")\s*:/g)].map(match => JSON.parse(match[1]));
  if (keys.length !== new Set(keys).size) throw new Error(`${name}: duplicate key`);
  for (const [key, text] of Object.entries(value)) {
    if (!/^[a-zA-Z][a-zA-Z0-9_.-]*$/.test(key)) throw new Error(`${name}: invalid key ${key}`);
    if (typeof text !== "string" || !text.trim()) throw new Error(`${name}: empty/non-string value at ${key}`);
    if (/<\/?[a-z][^>]*>/i.test(text) || /{{\s*-/.test(text)) throw new Error(`${name}: HTML or unescaped interpolation is forbidden at ${key}`);
    const residue = text.replace(/{{\s*[a-zA-Z][\w]*\s*}}/g, "");
    if (residue.includes("{{") || residue.includes("}}")) throw new Error(`${name}: invalid placeholder syntax at ${key}`);
  }
  return value;
}
const placeholders = text => [...new Set([...text.matchAll(/{{\s*(\w+)\s*}}/g)].map(match => match[1]))].sort();
export function checkCatalogs(catalogs) {
  const entries = Object.entries(catalogs);
  const baseName = "zh-CN";
  const base = catalogs[baseName];
  if (!base) throw new Error("Missing Chinese source catalog");
  const keys = Object.keys(base).sort();
  const missingTranslations = {};
  for (const [locale, catalog] of entries) {
    const actual = Object.keys(catalog).sort();
    missingTranslations[locale] = keys.filter(key => !Object.hasOwn(catalog, key)).length;
    for (const key of actual) {
      if (!Object.hasOwn(base, key)) throw new Error(`${locale}: unknown key ${key} (absent from ${baseName})`);
      if (JSON.stringify(placeholders(base[key])) !== JSON.stringify(placeholders(catalog[key]))) throw new Error(`${locale}: placeholder mismatch at ${key}`);
      const stem = key.replace(/_(one|other)$/, "");
      if (Object.hasOwn(base, stem + "_one") || Object.hasOwn(base, stem + "_other")) {
        if (![stem, stem + "_one", stem + "_other"].every(candidate => candidate in catalog)) throw new Error(`${locale}: incomplete plural family ${stem}`);
        if (!placeholders(catalog[key]).includes("count")) throw new Error(`${locale}: plural must use count at ${key}`);
      }
    }
  }
  return { locales: entries.map(([locale]) => locale), sourceKeys: keys.length, missingTranslations };
}
export function generateMessageTypes(catalog) {
  const keys = Object.keys(catalog).sort();
  const lines = ["// Generated by scripts/check-i18n.mjs --write-types. Do not edit by hand.",
    "export interface MessageParameters {"];
  for (const key of keys) {
    const params = placeholders(catalog[key]);
    const value = params.length ? "{ " + params.map(p => `${JSON.stringify(p)}: ${p === "count" ? "number" : "string | number"}`).join("; ") + " }" : "undefined";
    lines.push(`  ${JSON.stringify(key)}: ${value};`);
  }
  lines.push("}", "export type MessageKey = keyof MessageParameters;", "export type MessageArguments<K extends MessageKey> = MessageParameters[K] extends undefined", "  ? [] : [options: MessageParameters[K]];", "");
  return lines.join("\n");
}
function main() {
  const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
  const directory = path.join(root, "src/app/shared/i18n");
  const catalogs = Object.fromEntries(["zh-CN", "en-US"].map(locale => [locale, readFlatCatalog(fs.readFileSync(path.join(directory, "locales", locale + ".json"), "utf8"), locale)]));
  const result = checkCatalogs(catalogs);
  const expectedTypes = generateMessageTypes(catalogs["zh-CN"]);
  const typePath = path.join(directory, "messageTypes.ts");
  if (process.argv.includes("--write-types")) fs.writeFileSync(typePath, expectedTypes);
  else if (fs.readFileSync(typePath, "utf8").replace(/\r\n/g, "\n") !== expectedTypes) throw new Error("messageTypes.ts is stale. Run node scripts/check-i18n.mjs --write-types and review/commit the generated file.");
  console.log(JSON.stringify({ status: "passed", ...result, scope: "bundled catalogs and generated types; NOT whole-application translation coverage" }, null, 2));
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try { main(); } catch (error) { console.error(error.message); process.exitCode = 1; }
}
