import "fake-indexeddb/auto";
import { webcrypto } from "node:crypto";
import { act, renderHook } from "@testing-library/react";
import { beforeEach, expect, test, vi } from "vitest";
import { createObjectStorage } from "../app/features/objects/objectStorage";
import { createObjectRepository } from "../app/features/objects/objectRepository";
import { createPaperProjectRepository } from "../app/features/paper-projects/paperProjectRepository";
import { usePaperAttachmentController } from "../app/controllers/usePaperAttachmentController";
import { objectText, refOf } from "../app/features/objects/object.types";
beforeEach(() => vi.stubGlobal("crypto", webcrypto));
test("attachment editor saves Markdown revisions and preserves the draft when another editor changes the note", async () => {
  const scope = crypto.randomUUID(), storage = createObjectStorage(scope, () => scope);
  const repository = createObjectRepository(storage, scope), projects = createPaperProjectRepository(storage, scope);
  const openEditor = vi.fn(), openBoard = vi.fn();
  const { result } = renderHook(() => usePaperAttachmentController({ repository, projects, openEditor, openBoard }));
  const paper = { id: "p", title: "Paper" };
  await act(async () => { await result.current.create(paper, "note", "实验笔记"); });
  expect(openEditor).toHaveBeenCalledOnce();
  act(() => result.current.setDraft("# 实验\n\n$$x^2$$"));
  await act(async () => { await result.current.save(); });
  const project = await projects.ensurePaperProject({ paperId: paper.id, title: paper.title });
  const asset = (await projects.listAssets(project.projectId))[0];
  expect(objectText(await repository.get(asset.ref!))).toContain("$$x^2$$");
  const original = result.current.session!.object;
  await repository.editNote(refOf(original), "另一个编辑器的内容");
  act(() => result.current.setDraft("当前窗口未保存的想法"));
  await act(async () => { await result.current.save(); });
  expect(result.current.error).toContain("草稿仍保留");
  expect(result.current.session!.draft).toBe("当前窗口未保存的想法");
  expect(objectText(await repository.resolveLatest(original.objectId))).toBe("另一个编辑器的内容");
  await act(async () => { await result.current.create(paper, "board", "实验画布"); });
  expect(openBoard).toHaveBeenCalledWith(expect.objectContaining({ kind: "workspace.board", title: "实验画布" }));
  expect(await projects.listAssets(project.projectId)).toHaveLength(2);
});
