import { useEffect, useRef, useState } from "react";
import { Button, Field, FluentProvider, Input, Select, Tab, TabList, Textarea, webDarkTheme, webLightTheme } from "@fluentui/react-components";
import { AddRegular, PlayRegular, SaveRegular } from "@fluentui/react-icons";
import { useExtensionWorkbench } from "../extensions/extensionWorkbenchContext";
import { downloadExtensionJson } from "../extensions/ExtensionViews";
import { paperLensPackage } from "../extensions/paperLensPackage";
import { buildExtensionPackage, type BoardTemplate, type ValidatedExtension } from "../extensions/extensionPackage";
import type { ExtensionDraft, DraftChange, TrialReport } from "./extensionDraftStore";
import { StudioGraph } from "./StudioGraph";
import { compileWorkflow, type WorkflowDefinition } from "../workflows/workflowDefinition";
import { operationCatalog, operationIds } from "../workflows/operationCatalog";
import { createBlockRegistry, blockRegistryCapabilities, type DerivedBlockDefinition } from "../visual-blocks/blockRegistry";
import { ComponentTreeView } from "../visual-blocks/ComponentTreeView";
import { SchemaFields } from "../extensions/SchemaFields";
import { parseDataSchema, schemaDefaults, type JsonObject } from "../extensions/extensionSchema";
import "./workflowStudio.css";

export function WorkflowStudio() {
  const host = useExtensionWorkbench(), model = host?.studio;
  const [drafts, setDrafts] = useState<ExtensionDraft[]>([]), [draft, setDraft] = useState<ExtensionDraft>();
  const [tab, setTab] = useState("composition"), [path, setPath] = useState("liteasy.extension.json"), [text, setText] = useState("");
  const [error, setError] = useState(""), [busy, setBusy] = useState(false), [preview, setPreview] = useState<ValidatedExtension>(), [report, setReport] = useState<TrialReport>();
  const [selectedNode, setSelectedNode] = useState(""), [operator, setOperator] = useState<string>("core.value");
  const [dark, setDark] = useState(false), [narrow, setNarrow] = useState(false), [request, setRequest] = useState(""), [proposal, setProposal] = useState<{ revision: string; changes: DraftChange[] }>();
  const importFile = useRef<HTMLInputElement>(null), abort = useRef<AbortController>();
  const dirty = !!draft && text !== (draft.files[path] ?? "");
  useEffect(() => { if (!model) return; let alive = true; const reload = () => void model.drafts.list().then((items) => { if (alive) setDrafts(items); }); reload(); const dispose = model.drafts.subscribe(reload); return () => { alive = false; dispose(); abort.current?.abort(); }; }, [model]);
  useEffect(() => { setText(draft?.files[path] ?? ""); setPreview(undefined); setReport(undefined); }, [draft, path]);
  if (!host || !model) return <p>正在加载制作工作台…</p>;
  async function run(action: () => Promise<unknown>) { setBusy(true); setError(""); try { await action(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } }
  const paths = draft ? Object.keys(draft.files).filter((file) => tab === "composition" ? file.startsWith("templates/") : tab === "type" ? file.startsWith("blocks/") : tab === "workflow" ? file.startsWith("workflows/") : tab === "settings" ? file.startsWith("settings/") : true) : [];
  const choose = (value: ExtensionDraft) => { setDraft(value); setPath(Object.keys(value.files).find((file) => file.startsWith("templates/")) ?? "liteasy.extension.json"); setProposal(undefined); };
  const updateJson = (value: unknown) => setText(JSON.stringify(value, null, 2));
  let parsed: unknown; try { parsed = JSON.parse(text); } catch { /* Source editor retains incomplete drafts. */ }
  const document = parsed as Record<string, unknown> | undefined;
  const workflow = document?.schema === "liteasy.workflow/v2" ? document as unknown as WorkflowDefinition : undefined;
  const composition = document?.schema === "liteasy.board-template/v1" ? document as unknown as BoardTemplate : undefined;
  let type: ReturnType<ReturnType<typeof createBlockRegistry>["resolve"]> | undefined;
  try { if (tab === "type" && draft && parsed) { const definitions = Object.entries(draft.files).filter(([file]) => file.startsWith("blocks/")).map(([file, source]) => JSON.parse(file === path ? text : source) as DerivedBlockDefinition); const registry = createBlockRegistry(definitions); const item = parsed as DerivedBlockDefinition; type = registry.resolve(item.id, item.version); } } catch { /* Validation gives structured diagnostics on request. */ }
  return <section className="extension-page workflow-studio"><header><div><h1>制作工作台</h1><p>用基础块组合自己的研究方式；内容、布局、流程分别保存。</p></div><Button icon={<AddRegular />} disabled={busy || dirty} onClick={() => void run(async () => { const files = { ...(await paperLensPackage()).files }; const manifest = JSON.parse(files["liteasy.extension.json"]); const original = manifest.id; manifest.id = `plugin.personal-${crypto.randomUUID().slice(0, 8)}`; manifest.name = "我的论文比较台"; manifest.version = "1.0.0"; for (const file of Object.keys(files)) files[file] = files[file].split(original).join(manifest.id); files["liteasy.extension.json"] = JSON.stringify(manifest, null, 2); choose(await model.drafts.create(manifest.name, files)); })}>从论文比较模板开始</Button></header>
    <div className="extension-toolbar"><Select aria-label="选择扩展草稿" value={draft?.id ?? ""} disabled={dirty || busy} onChange={(_, data) => void run(async () => choose(await model.drafts.get(data.value)))}><option value="" disabled>选择草稿</option>{drafts.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</Select><Button disabled={dirty || busy} onClick={() => importFile.current?.click()}>导入项目</Button><Button onClick={() => host.openRuns()}>运行记录</Button></div>
    <input ref={importFile} hidden type="file" accept=".json" onChange={(event) => { const file = event.target.files?.[0]; event.target.value = ""; if (file) void run(async () => { if (file.size > 24 * 1024 * 1024) throw new Error("包文件过大。"); const { validateExtensionPackage } = await import("../extensions/extensionPackage"); const pkg = await validateExtensionPackage(JSON.parse(await file.text())); choose(await model.drafts.create(pkg.manifest.name, pkg.bundle.files)); }); }} />
    {draft ? <><div className="extension-toolbar"><strong>{draft.title}</strong><span>{dirty ? "未保存" : "草稿已保存"}</span><Button icon={<SaveRegular />} disabled={!dirty || busy} onClick={() => void run(async () => setDraft(await model.drafts.patch(draft.id, draft.revision, [{ path, text }], "user")))}>保存草稿</Button><Button disabled={dirty || busy} onClick={() => void run(async () => setPreview(await model.drafts.validate(draft.id)))}>校验与预览</Button><Button icon={<PlayRegular />} disabled={dirty || busy} onClick={() => void run(async () => { const value = await model.service.call("liteasy_extension_trial", { id: draft.id }, { writable: true }); setReport(value as TrialReport); })}>隔离样例试跑</Button><Button disabled={dirty || busy || !report?.passed} onClick={() => void run(async () => { const pkg = await model.drafts.publish(draft.id, host.packages.store); setError(`已发布 ${pkg.manifest.version}；请在扩展中检查新增入口并启用。`); })}>发布本地版本</Button><Button disabled={dirty} onClick={() => void run(async () => downloadExtensionJson(`${draft.title}.liteasy-extension.json`, await buildExtensionPackage(draft.files)))}>导出包</Button></div>
      <TabList selectedValue={tab} onTabSelect={(_, data) => { setTab(String(data.value)); }}><Tab value="composition">组合</Tab><Tab value="type">类型</Tab><Tab value="workflow">流程</Tab><Tab value="settings">设置</Tab><Tab value="source">源码</Tab><Tab value="api">API 目录</Tab></TabList>
      {tab === "api" ? <div><p>共享基础能力：{blockRegistryCapabilities.join(" · ")}</p>{operationIds.map((id) => <details key={id}><summary>{id} · {operationCatalog[id].effect}</summary><p>版本 {operationCatalog[id].version} · 重试 {operationCatalog[id].retry} · {operationCatalog[id].capability ?? "无额外权限"}</p></details>)}</div> : <><Select aria-label="项目文件" disabled={dirty} value={path} onChange={(_, data) => { setPath(data.value); setSelectedNode(""); }}>{[...new Set([path, ...paths])].map((file) => <option key={file}>{file}</option>)}</Select>
      {(workflow || composition) && (tab === "workflow" || tab === "composition") ? <><StudioGraph value={workflow ?? composition!} onSelect={setSelectedNode} onChange={updateJson} />{workflow ? <div className="studio-step-list" aria-label="工作流步骤列表">{workflow.nodes.map((node) => <Button key={node.id} appearance={selectedNode === node.id ? "secondary" : "subtle"} onClick={() => setSelectedNode(node.id)}>{node.title} · {node.operation.id}</Button>)}<Select aria-label="添加的操作类型" value={operator} onChange={(_, data) => setOperator(data.value)}>{operationIds.map((id) => <option key={id}>{id}</option>)}</Select><Button onClick={() => { const id = `node-${crypto.randomUUID().slice(0, 8)}`; updateJson({ ...workflow, nodes: [...workflow.nodes, { id, title: "新步骤", operation: { id: operator, version: "1.0.0" }, input: {}, retries: 0, breakpoint: false }] }); setSelectedNode(id); }}>添加步骤</Button><Button disabled={!selectedNode} onClick={() => updateJson({ ...workflow, nodes: workflow.nodes.map((node) => node.id === selectedNode ? { ...node, breakpoint: !node.breakpoint } : node) })}>切换断点</Button><Button disabled={!selectedNode} onClick={() => updateJson({ ...workflow, nodes: workflow.nodes.filter((node) => node.id !== selectedNode), edges: workflow.edges.filter((edge) => edge.from !== selectedNode && edge.to !== selectedNode) })}>移除步骤</Button></div> : null}</> : null}
      {type ? <div className="studio-type-preview"><p>继承 {type.family} · {blockRegistryCapabilities.join(" / ")}</p><SchemaFields key={`${path}:${type.version}`} schema={type.dataSchema} value={type.defaults} onChange={(defaults) => updateJson({ ...document, defaults })} /><FluentProvider theme={dark ? webDarkTheme : webLightTheme}>{type.templates.map((tree, index) => <ComponentTreeView key={index} tree={tree} data={type!.defaults} openPath={host.openLink} />)}</FluentProvider></div> : null}
      {tab === "settings" && document?.type === "object" ? (() => { try { const schema = parseDataSchema(document); return <SchemaFields schema={schema} value={schemaDefaults(schema) as JsonObject} onChange={(value) => updateJson({ ...schema, properties: Object.fromEntries(Object.entries(schema.properties ?? {}).map(([key, field]) => [key, { ...field, default: value[key] }])) })} />; } catch { return null; } })() : null}
      <Field label={workflow ? `定义与绑定${selectedNode ? ` · 选中 ${selectedNode}` : ""}` : "文件内容"}><Textarea className="studio-source" aria-label="扩展源文件" resize="vertical" value={text} onChange={(_, data) => setText(data.value)} /></Field></>}
      {preview ? <section className="studio-preview"><div className="extension-toolbar"><h2>实际组件预览</h2><Button onClick={() => setDark(!dark)}>{dark ? "浅色" : "深色"}</Button><Button onClick={() => setNarrow(!narrow)}>{narrow ? "正常宽度" : "窄栏"}</Button></div><FluentProvider theme={dark ? webDarkTheme : webLightTheme} style={{ maxWidth: narrow ? 320 : undefined }}><p>{preview.manifest.name} · {preview.manifest.version}</p>{preview.templates.map((template) => <section key={template.id}><h3>{template.title}</h3>{template.cards.map((card) => { const registry = createBlockRegistry(preview.blocks), type = registry.resolve(card.type.id, card.type.version), data = registry.instantiate(card.type.id, card.type.version, card.data); return <article key={card.id} className="extension-library-card"><h4>{card.title}</h4>{type.templates.map((tree, index) => <ComponentTreeView key={index} tree={tree} data={data} openPath={host.openLink} />)}</article>; })}</section>)}</FluentProvider></section> : null}
      {report ? <section><h2>样例报告 · {report.passed ? "通过" : "未通过"}</h2>{report.cases.map((item, i) => <p key={i}>{item.name} · {item.passed ? "通过" : item.error}</p>)}</section> : null}
      <details><summary>AI 制作助手</summary><Textarea aria-label="描述扩展需求" value={request} onChange={(_, data) => setRequest(data.value)} placeholder="描述输入、输出、保存位置，以及希望如何组织内容" /><Button disabled={busy || dirty || !request.trim()} onClick={() => void run(async () => { abort.current?.abort(); abort.current = new AbortController(); setProposal({ revision: draft.revision, changes: await model.propose(draft, request, abort.current.signal) }); })}>生成草稿变更</Button>{busy ? <Button onClick={() => abort.current?.abort()}>停止生成</Button> : null}{proposal ? <><h3>待应用变更</h3>{proposal.changes.map((change) => <details key={change.path}><summary>{change.path} · {change.text === null ? "删除" : draft.files[change.path] ? "修改" : "新增"}</summary><div className="studio-diff"><pre>{draft.files[change.path] ?? ""}</pre><pre>{change.text ?? ""}</pre></div></details>)}<Button disabled={busy || dirty} onClick={() => void run(async () => { setDraft(await model.drafts.patch(draft.id, proposal.revision, proposal.changes, "ai")); setProposal(undefined); })}>应用到草稿</Button></> : null}</details>
    </> : <p>从模板或本地项目开始，也可以让连接到 Liteasy 的 AI 通过 MCP 创建草稿。</p>}{error ? <p role="status">{error}</p> : null}
  </section>;
}
