import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";

test("launches AI from the top bar with current, opened, and directory papers in light and dark themes", async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.addInitScript(() => localStorage.setItem("liteasy.account.suppress-login-reminder.v1", "true"));
  const pdf = await readFile("public/manual-preview/das24a.pdf");
  await page.route("**/manual-preview/**/*.pdf", (route) => route.fulfill({ body: pdf, contentType: "application/pdf" }));
  await page.goto("/?pdf-highlight-fixture#ai-workbench");
  const top = page.getByRole("toolbar", { name: "工作区命令栏" });
  const ai = top.getByRole("button", { name: "AI 工作台" });
  await expect(ai).toHaveText("AI");
  await expect(page.getByRole("button", { name: "AI 薄读", exact: true })).toBeVisible();
  await expect(page.locator(".floating-modality-launcher")).toHaveCount(0);
  await expect(page.getByRole("button", { name: "锁定选中文献集", exact: true })).toHaveCount(0);
  await ai.click();
  const dialog = page.getByRole("dialog", { name: /论文工作台/ });
  await expect(dialog.getByRole("checkbox", { name: /Current Research/ })).toBeChecked();
  await expect(dialog.getByRole("checkbox", { name: /Recent Research/ })).not.toBeChecked();
  await expect(dialog.getByRole("button", { name: "生成 PPT", exact: true })).toBeDisabled();
  await dialog.getByRole("button", { name: "纳入已打开论文" }).click();
  await dialog.getByRole("tab", { name: "文献目录" }).click();
  await dialog.getByRole("textbox", { name: "搜索任务论文" }).fill("Methods");
  await dialog.getByRole("checkbox", { name: /Archived Methods/ }).check();
  await expect(dialog.getByText("已选 3 篇")).toBeVisible();
  await dialog.getByRole("button", { name: "确认选择", exact: true }).click();
  await expect(dialog.getByRole("button", { name: "生成 PPT", exact: true })).toBeEnabled();
  await expect(dialog.getByLabel("已确认的任务论文")).toContainText("Current Research");
  await dialog.getByRole("textbox", { name: "搜索任务论文" }).fill("");
  expect(await dialog.evaluate((element) => element.getBoundingClientRect().width)).toBeGreaterThan(800);
  await page.screenshot({ path: testInfo.outputPath("ai-workbench-light.png") });
  await page.evaluate(() => window.dispatchEvent(new CustomEvent("liteasy:appearance-change", { detail: "dark" })));
  await expect(page.locator("html")).toHaveAttribute("data-color-scheme", "dark");
  await expect(dialog.getByRole("button", { name: "生成 PPT", exact: true })).toHaveCSS("color", "rgb(255, 255, 255)");
  await page.screenshot({ path: testInfo.outputPath("ai-workbench-dark.png") });
  await dialog.getByRole("checkbox", { name: /Recent Research/ }).uncheck();
  await expect(dialog.getByRole("button", { name: "生成 PPT", exact: true })).toBeDisabled();
  await dialog.getByRole("button", { name: "关闭 AI 工作台" }).click();
  await page.getByRole("tab", { name: "Recent Research", exact: true }).click();
  await ai.click();
  await expect(dialog.getByRole("checkbox", { name: /Recent Research/ })).toBeChecked();
  await expect(dialog.getByRole("checkbox", { name: /Current Research/ })).not.toBeChecked();
  await page.keyboard.press("Escape");
  await expect(dialog).toHaveCount(0);
  await expect(ai).toBeFocused();
  await page.setViewportSize({ width: 560, height: 800 });
  await expect(ai).toBeVisible();
  await ai.click();
  await expect(dialog).toBeVisible();
  const dimensions = await dialog.evaluate((element) => ({ right: element.getBoundingClientRect().right, width: window.innerWidth }));
  expect(dimensions.right).toBeLessThanOrEqual(dimensions.width);
});
