import { readFile } from "node:fs/promises";
import { expect, test } from "@playwright/test";

test("right-click and footer open the sidebar editor; saved metadata updates library and footer and survives reload", async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => { errors.push(error.message); console.error(error.message); });
  await page.addInitScript(() => localStorage.setItem("liteasy.account.suppress-login-reminder.v1", "true"));
  const pdf = await readFile(new URL("../../../../../../../development/test-data/pdf-selection/glyph-boundaries.pdf", import.meta.url));
  await page.route("**/manual-preview/das24a.pdf", (route) => route.fulfill({ body: pdf, contentType: "application/pdf" }));
  await page.setViewportSize({ width: 1600, height: 1000 });
  await page.goto("/?pdf-highlight-fixture#importable");
  await page.getByRole("navigation", { name: "左边栏导航" }).getByRole("button", { name: "文献库", exact: true }).dblclick();
  const library = page.getByRole("region", { name: "本地文献库", exact: true });
  await library.getByRole("button", { name: "das24a.pdf", exact: true }).click({ button: "right" });
  await page.getByRole("menuitem", { name: "编辑元信息", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "文献库", exact: true })).toHaveCount(0);
  const editor = page.getByRole("form", { name: "编辑文献元信息" });
  await expect(page.locator('[data-region="right"]').getByRole("tab", { name: / · 信息$/ })).toBeVisible();
  await expect(editor).toBeVisible();
  await editor.getByRole("textbox", { name: "标题", exact: true }).fill("Designing data-intensive applications");
  await editor.getByRole("combobox", { name: "条目类型" }).selectOption("book");
  await editor.getByRole("button", { name: "添加作者", exact: true }).click();
  await editor.getByRole("textbox", { name: "作者 1", exact: true }).fill("Kleppmann, Martin");
  await editor.getByRole("textbox", { name: "出版日期", exact: true }).fill("2026-10");
  await editor.getByRole("textbox", { name: "出版社", exact: true }).fill("O'Reilly");
  await editor.getByRole("textbox", { name: "版次", exact: true }).fill("2nd edition");
  await editor.getByRole("textbox", { name: "DOI", exact: true }).fill("10.1234/manual");
  await editor.getByRole("textbox", { name: "摘要", exact: true }).fill("Reliable, scalable systems.");
  await page.screenshot({ path: testInfo.outputPath("bibliographic-editor.png"), fullPage: true });
  await editor.getByRole("button", { name: "保存元信息", exact: true }).click();
  await expect(page.getByRole("region", { name: "文献信息", exact: true }).getByRole("status")).toContainText("元信息已保存");
  const updated = library.getByRole("button", { name: "Designing data-intensive applications", exact: true });
  await expect(updated).toBeVisible();
  const footer = page.getByRole("contentinfo", { name: "文件状态栏" });
  await expect(footer).toContainText("Kleppmann, Martin");
  await expect(footer).toContainText("O'Reilly");
  await page.locator(".bibliographic-summary-body").evaluate((element) => { element.scrollTop = 0; });
  await page.screenshot({ path: testInfo.outputPath("bibliographic-editor-saved.png"), fullPage: true });
  await page.getByRole("button", { name: /^关闭 .* · 信息$/ }).click();
  await updated.click();
  await footer.getByRole("button", { name: "编辑元信息", exact: true }).click();
  await expect(editor.getByRole("textbox", { name: "标题", exact: true })).toHaveValue("Designing data-intensive applications");
  await editor.getByRole("textbox", { name: "DOI", exact: true }).fill("");
  await editor.getByRole("textbox", { name: "出版日期", exact: true }).fill("");
  await editor.getByRole("button", { name: "保存元信息", exact: true }).click();
  await expect(page.getByRole("region", { name: "文献信息", exact: true }).getByRole("status")).toContainText("元信息已保存");
  await expect(footer).not.toContainText("10.1234/manual");
  await page.reload();
  await updated.click();
  await footer.getByRole("button", { name: "编辑元信息", exact: true }).click();
  await expect(editor.getByRole("textbox", { name: "DOI", exact: true })).toHaveValue("");
  await expect(editor.getByRole("textbox", { name: "出版日期", exact: true })).toHaveValue("");
  await footer.getByRole("button", { name: "展开文件元信息", exact: true }).click();
  const details = page.getByRole("complementary", { name: "文件元信息" });
  await expect(details).toContainText("2nd edition");
  await expect(details).toContainText("Reliable, scalable systems.");
  expect(errors).toEqual([]);
});
