import { readFile } from "node:fs/promises";
import { expect, test } from "@playwright/test";

test("a paper Markdown attachment drags into chat and keeps its reading font size", async ({ page }, testInfo) => {
  test.setTimeout(90_000);
  const pdf = await readFile(new URL("../../../../../../../development/test-data/pdf-selection/glyph-boundaries.pdf", import.meta.url));
  await page.route("**/manual-preview/das24a.pdf", (route) => route.fulfill({ body: pdf, contentType: "application/pdf" }));
  await page.setViewportSize({ width: 1800, height: 1050 });
  await page.goto("/?pdf-highlight-fixture#importable");
  const library = page.getByRole("region", { name: "本地文献库", exact: true });
  const paper = library.getByRole("button", { name: "das24a.pdf", exact: true });
  await paper.click({ button: "right" });
  await page.getByRole("menuitem", { name: "新建 Markdown 笔记", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "新建 Markdown 笔记" });
  await dialog.getByRole("textbox", { name: "论文附件名称" }).fill("CicN");
  await dialog.getByRole("button", { name: "创建", exact: true }).click();
  const editor = page.getByRole("region", { name: "论文 Markdown 笔记", exact: true });
  await editor.getByRole("textbox", { name: "论文笔记 Markdown 源码" }).fill("# CicN\n\nCicada uses optimistic concurrency control.");
  await editor.getByRole("button", { name: "保存", exact: true }).click();
  await expect(editor.getByRole("button", { name: "保存", exact: true })).toBeDisabled();
  await editor.getByRole("button", { name: "阅读", exact: true }).click();
  await editor.getByRole("button", { name: "调整 Markdown 字号" }).click();
  const slider = page.getByRole("slider", { name: "Markdown 字号" });
  await slider.focus();
  await slider.press("Home");
  for (let count = 0; count < 12; count += 1) await slider.press("ArrowRight");
  await expect(slider).toHaveValue("24");
  await slider.press("Escape");
  const paragraph = editor.getByText("Cicada uses optimistic concurrency control.", { exact: true });
  await expect(paragraph).toHaveCSS("font-size", "24px");
  const disclosure = library.getByRole("button", { name: /展开 das24a.pdf 的 \d+ 个附件/ });
  await disclosure.click();
  const note = library.getByRole("button", { name: "打开论文文件：CicN", exact: true });
  await note.dragTo(page.locator(".assistant-pane"));
  await expect(page.getByRole("button", { name: "移除上下文：CicN", exact: true })).toBeVisible();
  await editor.getByRole("button", { name: "编辑", exact: true }).click();
  await expect(editor.getByRole("textbox", { name: "论文笔记 Markdown 源码" })).toHaveCSS("font-size", "24px");
  await page.screenshot({ path: testInfo.outputPath("paper-note-context-font.png"), animations: "disabled" });
});
