import { expect, test } from "@playwright/test";

test("dropping a note into a connected Vault writes Markdown and protects subsequent external edits", async ({ page }, testInfo) => {
  test.setTimeout(90000);
  // Only the OS directory chooser is replaced. Handles, IndexedDB, Markdown
  // writes, reload, and competing file edits use Chromium's real filesystem.
  await page.addInitScript(() => {
    Object.defineProperty(window, "showDirectoryPicker", { configurable: true,
      value: async () => (await navigator.storage.getDirectory()).getDirectoryHandle("Research Vault", { create: true }) });
  });
  await page.setViewportSize({ width: 1600, height: 1000 });
  await page.goto("/");
  await page.getByRole("navigation", { name: "左边栏导航" }).getByRole("button", { name: "笔记", exact: true }).click();
  const notes = page.getByRole("region", { name: "笔记", exact: true });
  await notes.getByRole("button", { name: "新建笔记", exact: true }).click();
  await notes.getByRole("textbox", { name: "笔记正文" }).fill("Vault sample\n\n用户的研究记录。\n\n## AI review\n保留对照实验。");
  await notes.getByRole("button", { name: "保存", exact: true }).click();
  await notes.getByRole("button", { name: "连接文件夹 / Obsidian Vault", exact: true }).click();
  const vault = notes.getByRole("treeitem", { name: "extern/Research Vault", exact: true });
  await expect(vault).toBeVisible();
  await notes.getByRole("treeitem", { name: "Liteasy/个人笔记", exact: true }).click();
  await notes.getByRole("button", { name: "查看笔记 Vault sample", exact: true }).dragTo(vault);
  const readFile = () => page.evaluate(async () => {
    const directory = await (await navigator.storage.getDirectory()).getDirectoryHandle("Research Vault");
    return (await (await directory.getFileHandle("Vault sample.md")).getFile()).text();
  });
  await expect.poll(readFile).toContain("保留对照实验。");
  await vault.click();
  const file = notes.getByRole("button", { name: "查看笔记 Vault sample.md", exact: true });
  await expect(file).toBeVisible();
  await file.dblclick();
  const workspace = page.getByRole("region", { name: "Markdown 文件阅读与编辑" });
  await page.getByRole("navigation", { name: "左边栏导航" }).getByRole("button", { name: "设置", exact: true }).click();
  const settings = page.getByRole("region", { name: "应用设置" });
  await settings.getByRole("button", { name: "外观与阅读" }).click();
  const readerFont = settings.getByRole("combobox", { name: "非 PDF 阅读字体", exact: true });
  await readerFont.click();
  await readerFont.fill("Georgia");
  await page.getByRole("option", { name: "使用字体：Georgia", exact: true }).click();
  await page.getByRole("button", { name: "关闭 设置", exact: true }).click();
  await expect(workspace.locator(".external-note-preview")).toHaveCSS("font-family", "Georgia, sans-serif");
  await page.reload();
  await vault.click();
  await file.dblclick();
  await expect(workspace.locator(".external-note-preview")).toHaveCSS("font-family", "Georgia, sans-serif");
  await expect(page.locator('[data-region="main"] .external-note-editor')).toBeVisible();
  await workspace.getByRole("button", { name: "编辑", exact: true }).click();
  const editor = workspace.getByRole("textbox", { name: "Markdown 源码" });
  const longMarkdown = Array.from({ length: 600 }, (_, index) => `第 ${index + 1} 行：可编辑的研究记录。`).join("\n");
  await editor.fill(longMarkdown);
  const editorBox = await editor.boundingBox();
  const workspaceBox = await workspace.boundingBox();
  expect(editorBox!.height).toBeGreaterThan(workspaceBox!.height - 250);
  expect(editorBox!.y + editorBox!.height).toBeLessThanOrEqual(workspaceBox!.y + workspaceBox!.height);
  await editor.press("Control+End");
  expect(await editor.evaluate((element) => element.scrollTop)).toBeGreaterThan(500);
  const scrollTop = await editor.evaluate((element) => element.scrollTop);
  await workspace.getByRole("button", { name: "加粗", exact: true }).click();
  expect(await editor.evaluate((element) => element.scrollTop)).toBeCloseTo(scrollTop, 0);
  await editor.press("Control+z");
  await expect(editor).toHaveValue(longMarkdown);
  await editor.fill("研究结论");
  await editor.press("Home");
  await editor.press("Shift+End");
  await workspace.getByRole("button", { name: "标题与正文" }).click();
  await page.getByRole("menuitem", { name: "2 级标题", exact: true }).click();
  await expect(editor).toHaveValue("## 研究结论");
  await expect(editor).toBeFocused();
  await editor.press("Control+End");
  await workspace.getByRole("button", { name: "更多 Markdown 工具" }).click();
  await page.getByRole("menuitem", { name: "独立公式", exact: true }).click();
  await expect(editor).toHaveValue("## 研究结论\n\n$$\nE = mc^2\n$$\n");
  await expect(editor).toBeFocused();
  await workspace.getByRole("button", { name: "保存", exact: true }).click();
  await expect.poll(readFile).toContain("E = mc^2");
  await workspace.getByRole("button", { name: "阅读", exact: true }).click();
  await expect(workspace.getByRole("heading", { name: "研究结论" })).toBeVisible();
  await expect(workspace.locator(".katex")).toBeVisible();
  await workspace.getByRole("button", { name: "编辑", exact: true }).click();
  await editor.fill(longMarkdown);
  await workspace.screenshot({ path: testInfo.outputPath("markdown-editor-light.png"), animations: "disabled" });
  await page.evaluate(() => window.dispatchEvent(new CustomEvent("liteasy:appearance-change", { detail: "dark" })));
  await workspace.evaluate((element) => { element.style.width = "420px"; });
  await expect(page.locator("html")).toHaveAttribute("data-color-scheme", "dark");
  expect(await workspace.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true);
  expect((await editor.boundingBox())!.height).toBeGreaterThan(300);
  await workspace.screenshot({ path: testInfo.outputPath("markdown-editor-dark-narrow.png"), animations: "disabled" });
  await workspace.evaluate((element) => { element.style.width = ""; });
  await editor.fill("Liteasy 尚未保存的编辑");
  await page.evaluate(async () => {
    const directory = await (await navigator.storage.getDirectory()).getDirectoryHandle("Research Vault");
    const writable = await (await directory.getFileHandle("Vault sample.md")).createWritable();
    await writable.write("Obsidian 中刚保存的内容"); await writable.close();
  });
  await workspace.getByRole("button", { name: "保存", exact: true }).click();
  await expect(workspace.getByRole("alert")).toContainText("其他应用");
  await expect(editor).toHaveValue("Liteasy 尚未保存的编辑");
  expect(await readFile()).toBe("Obsidian 中刚保存的内容");
  await page.screenshot({ path: testInfo.outputPath("vault-file-conflict.png"), fullPage: true, animations: "disabled" });
});
