import { expect, test } from "@playwright/test";
test("history and active page switchers support wrapped arrow navigation, dismissal and reopening a closed PDF", async ({ page }, info) => {
  await page.setViewportSize({ width: 1200, height: 850 });
  await page.addInitScript(() => localStorage.setItem("liteasy.account.suppress-login-reminder.v1", "true"));
  await page.goto("/?pdf-highlight-fixture#importable");
  await expect(page.getByRole("button", { name: "页面历史", exact: true })).toBeVisible({ timeout: 20_000 });
  await page.keyboard.press("F1");
  await page.getByRole("navigation", { name: "左边栏导航" }).getByRole("button", { name: "笔记", exact: true }).click();
  await page.keyboard.press("Control+,");
  await expect(page.getByRole("textbox", { name: "搜索设置" })).toBeVisible();
  await page.keyboard.press("Control+h");
  const dialog = page.getByRole("dialog", { name: "页面切换", exact: true });
  await expect(dialog).toBeVisible();
  await expect(dialog.getByRole("tab", { name: /历史页面/ })).toHaveAttribute("aria-selected", "true");
  await expect(dialog.getByRole("option").first()).toContainText("设置");
  await page.keyboard.press("Control+t");
  await expect(dialog.getByRole("tab", { name: /活跃页面/ })).toHaveAttribute("aria-selected", "true");
  const cards = dialog.getByRole("option");
  const count = await cards.count();
  expect(count).toBeGreaterThan(4);
  await page.keyboard.press("Home"); await expect(cards.first()).toBeFocused();
  await page.keyboard.press("ArrowRight"); await expect(cards.nth(1)).toBeFocused();
  const columns = await cards.evaluateAll((nodes) => nodes.filter((node) => (node as HTMLElement).offsetTop === (nodes[0] as HTMLElement).offsetTop).length);
  await page.keyboard.press("ArrowDown"); await expect(cards.nth(Math.min(count - 1, columns + 1))).toBeFocused();
  await page.keyboard.press("ArrowUp"); await expect(cards.nth(1)).toBeFocused();
  await page.screenshot({ path: info.outputPath("active-pages.png"), animations: "disabled" });
  await dialog.getByRole("option", { name: "文献库 · 工作区", exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await expect(page.locator(".shell-workspace-title")).toContainText("文献库");
  await page.getByRole("button", { name: "das24a.pdf", exact: true }).dblclick();
  await expect(page.getByRole("button", { name: "关闭 das24a.pdf", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "关闭 das24a.pdf", exact: true }).click();
  await page.keyboard.press("Control+t");
  await expect(dialog.getByRole("option", { name: "das24a.pdf · PDF", exact: true })).toHaveCount(0);
  await page.keyboard.press("Control+h");
  const closed = dialog.getByRole("option", { name: "das24a.pdf · PDF", exact: true });
  await expect(closed).toContainText("已关闭 · 可重新打开");
  await closed.focus(); await page.keyboard.press("Enter");
  await expect(dialog).toHaveCount(0);
  await expect(page.getByRole("tab", { name: "das24a.pdf", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "页面历史", exact: true }).click();
  await page.setViewportSize({ width: 380, height: 740 });
  expect(await dialog.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath("history-narrow.png"), animations: "disabled" });
  await page.keyboard.press("Escape");
  await expect(dialog).toHaveCount(0);
});
