import { readFile } from "node:fs/promises";
import { expect, test } from "@playwright/test";

test("reading typography and comments stay consistent with the PDF and survive reopening", async ({ page }, testInfo) => {
  test.setTimeout(90_000);
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.addInitScript(() => localStorage.setItem("liteasy.account.suppress-login-reminder.v1", "true"));
  const pdf = await readFile(new URL("../../../../../../../development/test-data/pdf-selection/glyph-boundaries.pdf", import.meta.url));
  await page.route("**/manual-preview/das24a.pdf", (route) => route.fulfill({ body: pdf, contentType: "application/pdf" }));
  await page.setViewportSize({ width: 1800, height: 1100 });
  await page.goto("/?pdf-highlight-fixture#importable");
  const paper = page.locator('.pdf-page-shell[data-page="1"]');
  await expect(paper.locator(".pdf-text-layer")).not.toBeEmpty({ timeout: 30_000 });
  const text = await paper.locator(".pdf-text-layer").innerText();
  await page.route("https://reading-parser.example.test/v1/pdf/mineru-extract", (route) => route.fulfill({ json: {
    pages: [{ page: 1, text }], markdown: `# 阅读测试\n\n${text}`, figures: [],
  } }));
  await page.getByRole("button", { name: "设置", exact: true }).click();
  await page.getByRole("region", { name: "应用设置" }).getByRole("button", { name: "论文与推荐" }).click();
  await page.getByLabel("论文内容解析").selectOption("custom");
  await page.getByLabel("MinerU API 地址").fill("https://reading-parser.example.test");
  await page.getByLabel("mineru API key", { exact: true }).fill("reading-test-key");
  await page.getByRole("button", { name: "保存密钥", exact: true }).last().click();
  await page.getByRole("button", { name: "关闭 设置", exact: true }).click();
  await page.getByRole("tab", { name: "das24a.pdf", exact: true }).click();
  await page.getByRole("button", { name: "MinerU 解析", exact: true }).click();
  await expect(page.getByRole("button", { name: "阅读模式", exact: true })).toBeVisible();
  const span = paper.locator(".pdf-text-layer span").filter({ hasText: /\S{4}/ }).first();
  const bounds = (await span.boundingBox())!;
  await page.mouse.move(bounds.x + 2, bounds.y + bounds.height / 2);
  await page.mouse.down();
  await page.mouse.move(bounds.x + bounds.width - 2, bounds.y + bounds.height / 2, { steps: 10 });
  await page.mouse.up();
  await page.getByLabel("选中文本批注菜单").getByRole("button", { name: "高亮", exact: true }).click();
  const row = page.locator(".pdf-annotation-item.highlight").first();
  await row.locator(".pdf-annotation-summary").click();
  await row.getByLabel("补充批注笔记").fill("来自 PDF 的评论");
  await row.getByRole("button", { name: "保存笔记", exact: true }).click();
  await page.getByRole("button", { name: "阅读模式", exact: true }).click();
  const reading = page.getByRole("region", { name: "论文阅读模式", exact: true });
  const comments = reading.getByRole("complementary", { name: "阅读模式批注" });
  await expect(comments).toContainText("来自 PDF 的评论");
  await expect.poll(() => page.evaluate(() => [...CSS.highlights.values()].reduce((sum, marks) => sum + marks.size, 0))).toBeGreaterThan(0);
  await expect.poll(() => page.locator(".pdf-page-canvas").evaluateAll((nodes) => nodes.reduce((sum, node) => sum + (node as HTMLCanvasElement).width * (node as HTMLCanvasElement).height, 0))).toBeLessThan(10);

  await reading.getByRole("button", { name: "页边批注", exact: true }).click();
  const margin = reading.getByRole("complementary", { name: "阅读页边批注", exact: true });
  await expect(comments).toHaveCount(0);
  await expect(margin.locator(".reading-margin-card")).toContainText("来自 PDF 的评论");
  const connectorError = () => reading.locator(".paper-reading-content").evaluate((root) => {
    const range = [...CSS.highlights.values()].flatMap((highlight) => [...highlight])[0] as Range;
    const rect = Array.from(range.getClientRects()).find((rect) => rect.width > 0 && rect.height > 0)!;
    const path = root.querySelector("[data-annotation-connector]")!;
    const start = path.getAttribute("d")!.match(/^M ([\d.-]+) ([\d.-]+)/)!;
    const bounds = root.getBoundingClientRect();
    return Math.abs(Number(start[2]) - (rect.top + rect.height / 2 - bounds.top));
  });
  await expect.poll(connectorError).toBeLessThan(2);

  await reading.getByRole("button", { name: "阅读排版", exact: true }).click();
  const size = page.getByRole("slider", { name: "阅读字号" });
  await size.focus(); await page.keyboard.press("End");
  await page.getByRole("combobox", { name: "阅读字体" }).click();
  await page.getByRole("option", { name: "无衬线 · 黑体", exact: true }).click();
  await page.getByRole("combobox", { name: "阅读页面宽度" }).selectOption("1080");
  await page.getByRole("combobox", { name: "阅读行距" }).selectOption("2.2");
  await page.keyboard.press("Escape");
  const body = reading.locator(".mineru-markdown").first();
  await expect(body).toHaveCSS("font-size", "30px");
  await expect(body).toHaveCSS("line-height", "66px");
  await expect(body).toHaveCSS("max-width", "1080px");
  await expect.poll(connectorError).toBeLessThan(2);
  await page.screenshot({ path: testInfo.outputPath("reading-margin-comments.png"), fullPage: true, animations: "disabled" });
  await margin.getByRole("button", { name: "编辑页边批注", exact: true }).click();
  await comments.getByRole("textbox", { name: "阅读批注内容" }).fill("阅读模式补充的评论");
  await comments.getByRole("combobox", { name: "标记颜色" }).selectOption("pink");
  await comments.getByRole("button", { name: "保存批注", exact: true }).click();
  await expect(comments).toHaveCount(0);
  await expect(margin.locator(".reading-margin-card")).toContainText("阅读模式补充的评论");
  await reading.getByRole("button", { name: "页边批注", exact: true }).click();
  await reading.getByRole("button", { name: /^批注（/ }).click();
  await expect(comments.getByRole("status")).toContainText("批注已保存");
  await comments.getByRole("button", { name: "查看 PDF", exact: true }).click();
  await expect(row.getByLabel("补充批注笔记")).toHaveValue("阅读模式补充的评论");
  await expect(page.locator(".pdf-overlay-mark.highlight").first()).toHaveCSS("background-color", "rgb(253, 121, 168)");
  await row.getByRole("button", { name: /阅读模式查看批注：/ }).click();
  await expect(reading.locator("[data-reading-comment-match]")).toBeVisible();
  const paragraph = body.locator("p").first();
  await paragraph.evaluate((element) => {
    const selection = window.getSelection()!;
    selection.removeAllRanges(); const range = document.createRange(); range.selectNodeContents(element); selection.addRange(range);
    element.dispatchEvent(new MouseEvent("mouseup", { bubbles: true }));
  });
  await expect(comments.getByRole("combobox", { name: "批注页码" })).toHaveValue("1");
  await comments.getByRole("textbox", { name: "阅读批注内容" }).fill("阅读模式新增的评论");
  await comments.getByRole("button", { name: "保存批注", exact: true }).click();
  await expect(comments.locator(".paper-reading-comment")).toHaveCount(2);
  await expect(comments.getByRole("textbox", { name: "阅读批注内容" })).toHaveCount(0);
  await page.screenshot({ path: testInfo.outputPath("reading-comments-and-typography.png"), fullPage: true, animations: "disabled" });
  await reading.getByRole("button", { name: "PDF 模式", exact: true }).click();
  await expect(page.locator(".pdf-annotation-item")).toHaveCount(2);
  await page.getByRole("button", { name: "阅读模式", exact: true }).click();
  await expect(body).toHaveCSS("font-size", "30px");
  await expect(comments).toContainText("阅读模式新增的评论");
  await comments.locator(".paper-reading-comment").filter({ hasText: "阅读模式新增的评论" }).getByRole("button", { name: "删除", exact: true }).click();
  await expect(comments.locator(".paper-reading-comment")).toHaveCount(1);
  await reading.getByRole("button", { name: "PDF 模式", exact: true }).click();
  await expect(page.locator(".pdf-annotation-item")).toHaveCount(1);
  expect(errors).toEqual([]);
});

test("long-form navigation, bookmarks, themes and focus retain the reading paragraph through reflow and reopening", async ({ page }, testInfo) => {
  test.setTimeout(90_000);
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.addInitScript(() => localStorage.setItem("liteasy.account.suppress-login-reminder.v1", "true"));
  const pdf = await readFile(new URL("../../../../../../../development/test-data/pdf-selection/glyph-boundaries.pdf", import.meta.url));
  await page.route("**/manual-preview/das24a.pdf", (route) => route.fulfill({ body: pdf, contentType: "application/pdf" }));
  const paragraph = "A scientific reader should preserve the original text, help readers navigate between sections, and remember the paragraph after changing typography. ".repeat(3);
  const markdown = `# Reader navigation\n\n${["Background", "Methods", "Results landmark", "Discussion"].map((heading) => `## ${heading}\n\n${Array.from({ length: 8 }, (_, i) => `Paragraph ${i + 1}. ${paragraph}`).join("\n\n")}`).join("\n\n")}`;
  await page.route("https://reading-navigation.example.test/v1/pdf/mineru-extract", (route) => route.fulfill({ json: {
    pages: [{ page: 1, text: markdown }], markdown, figures: [],
  } }));
  await page.setViewportSize({ width: 1600, height: 1050 });
  await page.goto("/?pdf-highlight-fixture#importable");
  await page.getByRole("button", { name: "设置", exact: true }).click();
  await page.getByRole("region", { name: "应用设置" }).getByRole("button", { name: "论文与推荐" }).click();
  await page.getByLabel("论文内容解析").selectOption("custom");
  await page.getByLabel("MinerU API 地址").fill("https://reading-navigation.example.test");
  await page.getByLabel("mineru API key", { exact: true }).fill("reading-test-key");
  await page.getByRole("button", { name: "保存密钥", exact: true }).last().click();
  await page.getByRole("button", { name: "关闭 设置", exact: true }).click();
  await page.getByRole("tab", { name: "das24a.pdf", exact: true }).click();
  await page.getByRole("button", { name: "MinerU 解析", exact: true }).click();
  await page.getByRole("button", { name: "阅读模式", exact: true }).click();
  const reading = page.getByRole("region", { name: "论文阅读模式", exact: true });
  const workspace = reading.locator(".paper-reading-workspace");
  const scroller = reading.locator(".paper-resource-tab");
  const heading = reading.locator(".mineru-markdown h2").filter({ hasText: "Results landmark" });
  const relativeTop = () => heading.evaluate((element) => element.getBoundingClientRect().top - element.closest(".paper-resource-tab")!.getBoundingClientRect().top);

  await reading.getByRole("button", { name: "阅读目录", exact: true }).click();
  await reading.getByRole("navigation", { name: "论文目录" }).getByRole("button", { name: "Results landmark", exact: true }).click();
  await expect.poll(async () => Math.abs(await relativeTop() - 16)).toBeLessThan(3);
  await expect.poll(() => reading.getByRole("progressbar", { name: "正文阅读位置" }).getAttribute("value")).not.toBe("0");
  await reading.getByRole("button", { name: "返回跳转前", exact: true }).click();
  await expect.poll(() => scroller.evaluate((element) => element.scrollTop)).toBeLessThan(200);
  await reading.getByRole("navigation", { name: "论文目录" }).getByRole("button", { name: "Results landmark", exact: true }).click();
  await reading.getByRole("tab", { name: "书签", exact: true }).click();
  await reading.getByRole("button", { name: "收藏当前位置", exact: true }).click();
  await expect(reading.locator(".paper-reading-bookmark")).toContainText("Results landmark");

  await reading.getByRole("button", { name: "阅读排版", exact: true }).click();
  await page.getByRole("combobox", { name: "阅读主题" }).selectOption("night");
  await page.getByRole("combobox", { name: "阅读段间距" }).selectOption("1.5");
  await page.getByRole("slider", { name: "阅读字号" }).focus();
  await page.keyboard.press("End");
  await page.keyboard.press("Escape");
  await expect.poll(async () => Math.abs(await relativeTop() - 16)).toBeLessThan(3);
  await expect(reading.locator(".mineru-markdown")).toHaveCSS("color", "rgb(220, 225, 229)");
  await reading.getByRole("button", { name: "专注阅读", exact: true }).click();
  await expect(workspace).toHaveClass(/is-focused/);
  await expect.poll(() => workspace.evaluate((element) => element.getBoundingClientRect().width)).toBe(1600);
  await expect.poll(async () => Math.abs(await relativeTop() - 16)).toBeLessThan(3);
  await reading.getByRole("button", { name: "返回跳转前", exact: true }).focus();
  await page.keyboard.press("Tab");
  await expect(reading.getByRole("button", { name: "阅读目录", exact: true })).toBeFocused();
  await reading.getByRole("button", { name: "阅读排版", exact: true }).click();
  await expect(page.getByRole("combobox", { name: "阅读主题" })).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(workspace).toHaveClass(/is-focused/);
  await page.screenshot({ path: testInfo.outputPath("focused-night-reading.png"), fullPage: true, animations: "disabled" });
  await page.keyboard.press("Escape");
  await expect(workspace).not.toHaveClass(/is-focused/);

  await workspace.focus(); await page.keyboard.press("Control+f");
  const search = reading.getByRole("textbox", { name: "查找阅读正文" });
  await expect(search).toBeFocused();
  await search.fill("Discussion");
  await expect(reading.getByRole("status").filter({ hasText: "1 个匹配段落" })).toBeVisible();
  await search.press("Enter");
  await expect(reading.locator("[data-reading-navigation-match]")).toHaveText("Discussion");
  await search.press("Escape");
  await reading.getByRole("button", { name: "返回跳转前", exact: true }).click();
  await expect.poll(async () => Math.abs(await relativeTop() - 16)).toBeLessThan(3);
  await reading.getByRole("button", { name: "PDF 模式", exact: true }).click();
  await page.getByRole("button", { name: "阅读模式", exact: true }).click();
  await expect.poll(async () => Math.abs(await relativeTop() - 16)).toBeLessThan(3);
  await expect(workspace).toHaveAttribute("data-reading-theme", "night");
  await reading.getByRole("button", { name: "阅读书签", exact: true }).click();
  await expect(reading.locator(".paper-reading-bookmark")).toContainText("Results landmark");
  await page.screenshot({ path: testInfo.outputPath("reading-bookmarks-and-progress.png"), fullPage: true, animations: "disabled" });

  // A reflowed note follows a distant paragraph, including scrolling and narrow panes.
  await reading.getByRole("button", { name: "阅读书签", exact: true }).click();
  await heading.evaluate((element) => {
    element.scrollIntoView({ block: "center" });
    const range = document.createRange(); range.selectNodeContents(element);
    const selection = window.getSelection()!; selection.removeAllRanges(); selection.addRange(range);
    element.dispatchEvent(new MouseEvent("mouseup", { bubbles: true }));
  });
  await reading.getByRole("combobox", { name: "标记类型", exact: true }).selectOption("note");
  await reading.getByRole("textbox", { name: "阅读批注内容", exact: true }).fill("重点核对实验结果。");
  await reading.getByRole("button", { name: "保存批注", exact: true }).click();
  await expect(reading.getByRole("textbox", { name: "阅读批注内容", exact: true })).toHaveCount(0);
  await page.evaluate(() => window.getSelection()?.removeAllRanges());
  await reading.getByRole("button", { name: "页边批注", exact: true }).click();
  await heading.evaluate((element) => element.scrollIntoView({ block: "center" }));
  const marginCard = reading.locator(".reading-margin-card");
  await expect(marginCard).toContainText("重点核对实验结果。");
  const anchorError = () => heading.evaluate((element) => {
    const root = element.closest(".paper-reading-content")!;
    const range = document.createRange(); range.selectNodeContents(element);
    const rect = range.getBoundingClientRect();
    const d = root.querySelector("[data-annotation-connector]")?.getAttribute("d");
    if (!d) return Infinity;
    const start = d.match(/^M ([\d.-]+) ([\d.-]+)/)!;
    return Math.abs(Number(start[2]) - (rect.top + rect.height / 2 - root.getBoundingClientRect().top));
  });
  await expect.poll(anchorError).toBeLessThan(2);
  await reading.locator(".paper-resource-tab").evaluate((element) => { element.scrollTop += 60; });
  await expect.poll(anchorError).toBeLessThan(2);
  await page.setViewportSize({ width: 1050, height: 1050 });
  await expect(reading.getByRole("button", { name: "加宽阅读区可查看页边连线" })).toBeVisible();
  await expect(marginCard).toHaveCount(0);
  await page.setViewportSize({ width: 1600, height: 1050 });
  await heading.evaluate((element) => element.scrollIntoView({ block: "center" }));
  await expect(marginCard).toContainText("重点核对实验结果。");
  await expect.poll(anchorError).toBeLessThan(2);
  await expect(marginCard).toHaveCSS("color", "rgb(220, 225, 229)");
  await expect(marginCard.getByRole("button", { name: "编辑页边批注" })).toHaveCSS("color", "rgb(220, 225, 229)");
  await page.screenshot({ path: testInfo.outputPath("reading-margin-night-and-scroll.png"), fullPage: true, animations: "disabled" });
  expect(errors).toEqual([]);
});
