import { readFile } from "node:fs/promises";
import { expect, test } from "@playwright/test";

test("reading typography and comments stay consistent with the PDF and survive reopening", async ({ page }, testInfo) => {
  test.setTimeout(90_000);
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.addInitScript(() => localStorage.setItem("liteasy.account.suppress-login-reminder.v1", "true"));
  const pdf = await readFile(new URL("../../../../../../../development/test-data/pdf-selection/glyph-boundaries.pdf", import.meta.url));
  await page.route("**/manual-preview/das24a.pdf", (route) => route.fulfill({ body: pdf, contentType: "application/pdf" }));
  await page.setViewportSize({ width: 1800, height: 1100 });
  await page.goto("/?pdf-highlight-fixture#importable");
  const paper = page.locator('.pdf-page-shell[data-page="1"]');
  await expect(paper.locator(".pdf-text-layer")).not.toBeEmpty({ timeout: 30_000 });
  const text = await paper.locator(".pdf-text-layer").innerText();
  await page.route("https://reading-parser.example.test/v1/pdf/mineru-extract", (route) => route.fulfill({ json: {
    pages: [{ page: 1, text }], markdown: `# 阅读测试\n\n${text}`, figures: [],
  } }));
  await page.getByRole("button", { name: "设置", exact: true }).click();
  await page.getByLabel("论文内容解析").selectOption("custom");
  await page.getByLabel("MinerU API 地址").fill("https://reading-parser.example.test");
  await page.getByLabel("mineru API key", { exact: true }).fill("reading-test-key");
  await page.getByRole("button", { name: "保存密钥", exact: true }).last().click();
  await page.getByRole("button", { name: "MinerU 解析", exact: true }).click();
  await expect(page.getByRole("button", { name: "阅读模式", exact: true })).toBeVisible();
  const span = paper.locator(".pdf-text-layer span").filter({ hasText: /\S{4}/ }).first();
  const bounds = (await span.boundingBox())!;
  await page.mouse.move(bounds.x + 2, bounds.y + bounds.height / 2);
  await page.mouse.down();
  await page.mouse.move(bounds.x + bounds.width - 2, bounds.y + bounds.height / 2, { steps: 10 });
  await page.mouse.up();
  await page.getByLabel("选中文本批注菜单").getByRole("button", { name: "高亮", exact: true }).click();
  const row = page.locator(".pdf-annotation-item.highlight").first();
  await row.locator(".pdf-annotation-summary").click();
  await row.getByLabel("补充批注笔记").fill("来自 PDF 的评论");
  await row.getByRole("button", { name: "保存笔记", exact: true }).click();
  await page.getByRole("button", { name: "阅读模式", exact: true }).click();
  const reading = page.getByRole("region", { name: "论文阅读模式", exact: true });
  const comments = reading.getByRole("complementary", { name: "阅读模式批注" });
  await expect(comments).toContainText("来自 PDF 的评论");
  await reading.getByRole("button", { name: "阅读排版", exact: true }).click();
  const size = page.getByRole("slider", { name: "阅读字号" });
  await size.focus(); await page.keyboard.press("End");
  await page.getByRole("combobox", { name: "阅读字体" }).selectOption("sans");
  await page.getByRole("combobox", { name: "阅读页面宽度" }).selectOption("1080");
  await page.getByRole("combobox", { name: "阅读行距" }).selectOption("2.2");
  await page.keyboard.press("Escape");
  const body = reading.locator(".mineru-markdown").first();
  await expect(body).toHaveCSS("font-size", "30px");
  await expect(body).toHaveCSS("line-height", "66px");
  await expect(body).toHaveCSS("max-width", "1080px");
  await comments.getByRole("button", { name: "编辑", exact: true }).click();
  await comments.getByRole("textbox", { name: "阅读批注内容" }).fill("阅读模式补充的评论");
  await comments.getByRole("button", { name: "保存批注", exact: true }).click();
  await expect(comments.getByRole("status")).toContainText("批注已保存");
  await comments.getByRole("button", { name: "查看 PDF", exact: true }).click();
  await expect(row.getByLabel("补充批注笔记")).toHaveValue("阅读模式补充的评论");
  await row.getByRole("button", { name: /阅读模式查看批注：/ }).click();
  await expect(reading.locator("[data-reading-comment-match]")).toBeVisible();
  const paragraph = body.locator("p").first();
  await paragraph.evaluate((element) => {
    const selection = window.getSelection()!;
    selection.removeAllRanges(); const range = document.createRange(); range.selectNodeContents(element); selection.addRange(range);
    element.dispatchEvent(new MouseEvent("mouseup", { bubbles: true }));
  });
  await expect(comments.getByRole("combobox", { name: "批注页码" })).toHaveValue("1");
  await comments.getByRole("textbox", { name: "阅读批注内容" }).fill("阅读模式新增的评论");
  await comments.getByRole("button", { name: "保存批注", exact: true }).click();
  await expect(comments.locator(".paper-reading-comment")).toHaveCount(2);
  await expect(comments.getByRole("textbox", { name: "阅读批注内容" })).toHaveCount(0);
  await page.screenshot({ path: testInfo.outputPath("reading-comments-and-typography.png"), fullPage: true, animations: "disabled" });
  await reading.getByRole("button", { name: "PDF 模式", exact: true }).click();
  await expect(page.locator(".pdf-annotation-item")).toHaveCount(2);
  await page.getByRole("button", { name: "阅读模式", exact: true }).click();
  await expect(body).toHaveCSS("font-size", "30px");
  await expect(comments).toContainText("阅读模式新增的评论");
  await comments.locator(".paper-reading-comment").filter({ hasText: "阅读模式新增的评论" }).getByRole("button", { name: "删除", exact: true }).click();
  await expect(comments.locator(".paper-reading-comment")).toHaveCount(1);
  await reading.getByRole("button", { name: "PDF 模式", exact: true }).click();
  await expect(page.locator(".pdf-annotation-item")).toHaveCount(1);
  expect(errors).toEqual([]);
});
