import { readFile } from "node:fs/promises";
import { expect, test } from "@playwright/test";

test("annotations, PDF text boxes, paper tabs, board cards and entire boards become chat context and move with the session", async ({ page }, testInfo) => {
  test.setTimeout(75_000);
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  const pdf = await readFile(new URL("../../../../../../../development/test-data/pdf-selection/glyph-boundaries.pdf", import.meta.url));
  await page.route("**/manual-preview/das24a.pdf", (route) => route.fulfill({ body: pdf, contentType: "application/pdf" }));
  await page.setViewportSize({ width: 1920, height: 1100 });
  await page.goto("/?pdf-highlight-fixture#importable");
  const paper = page.locator('.pdf-page-shell[data-page="1"]');
  await expect(paper.locator(".pdf-text-layer")).not.toBeEmpty({ timeout: 30_000 });
  const chat = page.locator(".assistant-pane");
  const context = page.getByLabel("已添加到对话上下文", { exact: true });
  const span = paper.locator(".pdf-text-layer span").filter({ hasText: /\S{4}/ }).first();
  const bounds = (await span.boundingBox())!;
  await page.mouse.move(bounds.x + 2, bounds.y + bounds.height / 2);
  await page.mouse.down();
  await page.mouse.move(bounds.x + bounds.width - 2, bounds.y + bounds.height / 2, { steps: 10 });
  await page.mouse.up();
  await page.getByLabel("选中文本批注菜单").getByRole("button", { name: "划线", exact: true }).click();
  const summary = page.locator(".pdf-annotation-summary").first();
  await summary.dragTo(chat);
  await expect(context.getByRole("button")).toHaveCount(1);
  await expect(page.locator("section.object-workbench")).toHaveCount(0);
  await page.getByRole("button", { name: "在 PDF 中添加 Markdown 文本框", exact: true }).click();
  const paperBounds = (await paper.boundingBox())!;
  await page.mouse.click(paperBounds.x + paperBounds.width * 0.3, paperBounds.y + paperBounds.height * 0.4);
  await page.getByRole("textbox", { name: "编辑第 1 页 Markdown 文本框" }).fill("拖入对话的 PDF 文字");
  await page.getByRole("button", { name: "保存 Markdown 文本框", exact: true }).click();
  await paper.getByRole("region", { name: "Markdown 文本框：第 1 页" }).dragTo(chat);
  await expect(context.getByRole("button")).toHaveCount(2);
  await page.getByRole("tab", { name: "das24a.pdf", exact: true }).dragTo(chat);
  await expect(context.getByRole("button")).toHaveCount(3);
  await page.getByRole("navigation", { name: "左边栏导航" }).getByRole("button", { name: "研究白板", exact: true }).click();
  const board = page.locator("section.object-workbench");
  await board.getByRole("button", { name: "添加笔记", exact: true }).click();
  await board.getByLabel("笔记内容", { exact: true }).fill("白板上的用户观点");
  await board.getByRole("button", { name: "新建笔记", exact: true }).click();
  await board.getByRole("button", { name: "收起工具", exact: true }).click();
  const card = board.locator(".object-placement");
  await expect(card).toHaveCount(1);
  const position = await card.getAttribute("style");
  await card.dragTo(chat);
  await expect(context.getByRole("button")).toHaveCount(4);
  await expect(card).toHaveAttribute("style", position!);
  await page.getByRole("tab", { name: "研究白板", exact: true }).dragTo(chat);
  await expect(context.getByRole("button")).toHaveCount(5);
  await expect(context).toContainText("1 个元素");
  await expect(board).toBeVisible();
  await page.getByPlaceholder("输入你的问题或命令").fill("请结合这些内容审阅我的观点");
  await page.getByRole("tab", { name: "Liteasy Chat", exact: true }).press("Alt+Shift+ArrowDown");
  await expect(page.locator(".dock-region-bottom .assistant-pane")).toBeVisible();
  await expect(context.getByRole("button")).toHaveCount(5);
  await expect(page.getByPlaceholder("输入你的问题或命令")).toHaveValue("请结合这些内容审阅我的观点");
  await expect(page.getByRole("button", { name: "发送", exact: true })).toBeInViewport();
  await expect(board).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("resource-context.png"), fullPage: true, animations: "disabled" });
  expect(errors).toEqual([]);
});
