import type { SettingKey } from "./settings.types";

export const settingsRegistry: Record<SettingKey, { label: string }> = {
  "thin_reading.mode": { label: "薄读模式" },
  "papers.metadata_provider": { label: "文献元信息服务" },
  "papers.metadata_endpoint": { label: "元信息 API 地址" },
  "papers.mineru_mode": { label: "论文解析服务" },
  "papers.mineru_endpoint": { label: "MinerU API 地址" },
  "network.recommendation.enabled": { label: "联网推荐" },
  "network.recommendation.sort_mode": { label: "推荐排序" },
  "assistant.public_audit.enabled": { label: "公开审计过程" },
  "profile.enabled": { label: "用户画像" },
  "assistant.default_output_mode": { label: "默认输出模式" },
  "assistant.language": { label: "回答语言" },
  "import.ocr_language": { label: "扫描 PDF OCR 语言" },
  "thin_reading.intuecho_endpoint": { label: "Intuecho 同步端点" },
  "models.default_provider": { label: "默认模型服务商" },
  "models.connection_mode": { label: "AI 接入方式" },
  "models.direct_provider": { label: "自备 API 服务商" },
  "models.direct_endpoint": { label: "自备 API 地址" },
  "models.direct_model": { label: "自备 API 模型" },
  "models.direct_protocol": { label: "自备 API 协议" },
  "models.direct_output_format": { label: "结构化输出方式" },
  "models.cloud_proxy_endpoint": { label: "云代理模型端点" },
  "models.control_plane_endpoint": { label: "云端控制平面端点" },
  "view.font_family": { label: "界面字体" },
  "view.font_size": { label: "界面字号" },
  "view.pdf_background": { label: "PDF 阅读底色" },
  "view.pdf_custom_background": { label: "自定义 PDF 底色" }
};
